version: '3.8'

services:
  jupiterhub:
    image: maxtever/jupyterhub:latest
    ports:
      - '8000:8000'
    environment:
      - JUPITERHUB_ADMIN_NAME=admin
    volumes:
      - ./data:/home/jovyan
    command: ["jupyterhub", "--ip=0.0.0.0", "--port=8000"]
    restart: always