
services: 
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports: 
      - "80:80"
    networks: 
      - frontend
      - backend
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  redis: 
    image: redis:latest
    container_name: redis
    restart: always
    depends_on:
      - nginx
    networks:
      - backend

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    restart: always
    depends_on:
      - redis
    networks:
      - backend

  mongodb:
    image: mongo:latest
    restart: always
    depends_on:
      - nginx
      - redis
      - python-app
    deploy:
      replicas: 2
    volumes:
      - mongo_data1:/data/db
    networks:
      - backend


volumes:
  mongo_data1:

networks:
  frontend:
  backend: