
services:
  jupyterhub:
    build: .
    ports:
      - '8000:8000'
    environment:
      - JUPYTERHUB_ADMIN_NAME=admin
    volumes:
      - ./data:/home/jovyan/all_notebooks
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/hub/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s