
services:
  jupyterhub:
    image: jupyterhub/jupyterhub:latest
    ports:
      - '8000:8000'
    environment:
      - JUPITERHUB_ADMIN_NAME=admin
    volumes:
      - ./data:/home/jovyan
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    command: ["jupyterhub", "--ip=0.0.0.0", "--port=8000"]
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/hub/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s