name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'  # Запускать пайплайн только при изменениях в папке .github/workflows
      - 'jupyter'
      - 'Dockerfile'  # Запускать пайплайн при изменениях в Dockerfile
      - 'docker-compose.yml'  # Запускать пайплайн при изменениях в docker-compose.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t maxtever/jupyterhub:latest ./jupyter

    - name: Install docker-compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Run docker-compose
      run: |
        cd jupyter
        docker-compose up -d
        sleep 30  # Даем время на запуск JupyterHub
        curl -sSf http://localhost:8000 > /dev/null
        docker-compose down